export interface Filters {
  toTime?: string | null;
  fromTime?: string | null;
  MSISDN?: string;
  vdn?: string;
  city?: string;
  limit?: string;
  category?: string;
  routedAtFromTime?: string;
  routedAtToTime?: string;
  vdnSource?: string;
  longCall?: any;
  abandonedCalls?: boolean;
  routedCalls?: boolean;
  subcategory?: string;
  second_subcategory?: string;
  subCategoryLevel1?: string;
  subCategoryLevel2?: string;
  sentiment?: string;
  sentiment_type?: string;
  tenantId?: string;
  subtenantId?: string;
  agentId?: string;
  companyId?: string;
  caseStatus?: string;
  id?: string;
  agentName?: string;
  repeatCall?: string;
  dropCall?: string;
  agentSentiment?: string;
  userSentiment?: string;
  clientId?: string;
  agentGroup?: string;
  call_id?: string;
  keyWord?: string;
  departmentId?: string;
  projectId?: string;
  project_id?: string;
  page?: string;
  page_size?: string;
  searchKey?: string;
  callID?: string;
  reportId?: string;
  agent_id?: string;
  [key: string]: any;
  parent_id?: any;
  type?: any;
}
