import { motion } from "framer-motion";

export function Footer() {
  return (
    <motion.footer
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="bg-card border-t border-border/50 p-2"
    >
      <div className="flex flex-col md:flex-row justify-between items-start gap-2">
        {/* Left side - AI Disclaimer */}
        <div className="text-xs text-muted-foreground">
          All reports are generated by AI. While we strive for accuracy, some errors may occur.
        </div>
        
        {/* Right side - Links */}
        <div className="flex flex-wrap items-center gap-4 text-xs justify-end">
          <a 
            href="https://www.globalwavenet.com/" 
            target="_blank" 
            rel="noopener noreferrer"
            className="text-muted-foreground hover:text-primary transition-colors"
          >
            Global Wavenet - 2024
          </a>
        </div>
      </div>
    </motion.footer>
  );
}
